defaults_ds={
          "input_height":None,
          "input_width":None,
          "n_classes":4,
          "verify_dataset":True,
          "batch_size":2,
          "validate":False,
          "val_images":None,
          "val_annotations":None,
          "val_batch_size":2,
          "auto_resume_checkpoint":False,
          "load_weights":None,
          "steps_per_epoch":512,
          "val_steps_per_epoch":12,
          "gen_use_multiprocessing":False,
          "ignore_zero_class":False,
          "optimizer_name":'adam',
          "do_augment":False,
          "augmentation_name":"aug_all",
          "callbacks":None,
          "custom_augmentation":None,
          "other_inputs_paths":None,
          "preprocessing":None,
          "read_image_type":1  # cv2.IMREAD_COLOR = 1 (rgb),
                             # cv2.IMREAD_GRAYSCALE = 0,
                             # cv2.IMREAD_UNCHANGED = -1 (4 channels like RGBA)
}